services:
  - type: web
    name: botexcel-landing
    runtime: node
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install; npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: BOTEXCEL_API_BASE
        value: https://api.botexcel.pro
      - key: NEXT_PUBLIC_BACKEND
        value: https://api.botexcel.pro
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
    domains:
      - botexcel.pro
      - www.botexcel.pro
    autoDeploy: true
    healthCheckPath: /
